services:

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql

    environment:
      MYSQL_ROOT_PASSWORD: king
      MYSQL_DATABASE: test_db

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s